language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run lint:style
- npm run lint:code
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: d+GzUY309/e40Pgr4f8VK6k5oJVTEj71AlU2g7F6oZrQjilZd5oj78IFylS3rWuHmrpAe/QkVnXqRyjrHpzKU0c2dztXsD+zfpZYc2nE22x1fYPTuTccE1qupW1TZGPMgX74F1AYUyJPP90QPVYW20TccCZXdGhLiRRT4G3ZwFtwrFGXR+Uy+dAOIK9v/UGjuRfN+bfhmrLuJcwQDb2n170SBklvqkzyIJiiwKLMPRTWsUKEJ8oWu34W82MBclck0Eq+aqk5Mb/31ow3GDqemPMkuvrbZuexhwxIVGfYDDlak/7IiHUyuisMGP6FmZPTxJiy4F0BcqVHfal+badAg+rblEYTrD5pQa99GZFlKuexhUsgEkSeR3erMRdtreENdh0XUC6hTIBvTqzzSKNmA1445uEaORQOxNLgAHAFJzJZbIATX1xGPBJgBwh6WscGc54YyuJhpbJd6Ht5TE/9O159II7sBvTLSTpsu4u0EHRw+kn8E+deUEsm27XAMNZC51FJpM4Mf2bD+MMFig1tXaZsAwXaPDsgQGZIsG/+37+b9htzIVRtmo0tSEe+65Gb8i1vIHkSktCOmWqhzl4JviAXZh6En/c68NLugVN75cheskCJX4d1M+FnEYS6bpmH2v5OFjmR0m9EVOpX+RbT2Atmr1RbJoz+vxd3GwaATqA=
  app: shri-h-4
